steps:
  # Build the image
  - name: "gcr.io/cloud-builders/docker"
    secretEnv: ["FINANCIAL_MODELING_PREP_API_KEY"]
    entrypoint: bash
    args:
      - -c
      - |
        docker build --network=cloudbuild \
          --build-arg FINANCIAL_MODELING_PREP_API_KEY=$$FINANCIAL_MODELING_PREP_API_KEY \
          -t "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA" \
          .

  # Push the image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args:
      - -c
      - |
        docker push "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA"

  # Deploy the image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy "$_CLOUD_RUN_SERVICE_NAME" \
          --image "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA" \
          --region "$_CLOUD_RUN_REGION" \
          --set-secrets FINANCIAL_MODELING_PREP_API_KEY=FINANCIAL_MODELING_PREP_API_KEY:latest \
          --allow-unauthenticated

images:
  - "$_ARTIFACT_REGISTRY_REGION-docker.pkg.dev/$_PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_ARTIFACT_REGISTRY_IMAGE_NAME:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/cannytrading-prod/secrets/FINANCIAL_MODELING_PREP_API_KEY/versions/latest"
      env: "FINANCIAL_MODELING_PREP_API_KEY"

substitutions:
  _PROJECT_ID: cannytrading-prod
  _ARTIFACT_REGISTRY_REGION: us-west1
  _ARTIFACT_REGISTRY_REPO_NAME: web-repository
  _ARTIFACT_REGISTRY_IMAGE_NAME: main
  _CLOUD_RUN_REGION: us-west1
  _CLOUD_RUN_SERVICE_NAME: cannytrading
