import "@/app/globals.css";
import { type Metadata } from "next";
import { Inter, Noto_Sans_SC } from "next/font/google";

import styles from "./layout.module.css";

type RootLayoutProps = { children: React.ReactNode };

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const noto_sans_sc = Noto_Sans_SC({
  subsets: ["latin"],
  variable: "--font-noto-sans-sc",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en-US" className={`${inter.variable} ${noto_sans_sc.variable}`}>
      <body className={styles.body}>{children}</body>
    </html>
  );
}

export default RootLayout;
