export type GicsSector =
  | "Communication Services"
  | "Consumer Discretionary"
  | "Consumer Staples"
  | "Energy"
  | "Financials"
  | "Health Care"
  | "Industrials"
  | "Information Technology"
  | "Materials"
  | "Real Estate"
  | "Utilities";

export type GicsIndustryGroup =
  | "Automobiles & Components"
  | "Banks"
  | "Capital Goods"
  | "Commercial & Professional Services"
  | "Consumer Discretionary Distribution & Retail"
  | "Consumer Durables & Apparel"
  | "Consumer Services"
  | "Consumer Staples Distribution & Retail"
  | "Energy"
  | "Equity Real Estate Investment Trusts (REITs)"
  | "Financial Services"
  | "Food, Beverage & Tobacco"
  | "Health Care Equipment & Services"
  | "Household & Personal Products"
  | "Insurance"
  | "Materials"
  | "Media & Entertainment"
  | "Pharmaceuticals, Biotechnology & Life Sciences"
  | "Real Estate Management & Development"
  | "Semiconductors & Semiconductor Equipment"
  | "Software & Services"
  | "Technology Hardware & Equipment"
  | "Telecommunication Services"
  | "Transportation"
  | "Utilities";

export type GicsIndustry =
  | "Aerospace & Defense"
  | "Air Freight & Logistics"
  | "Automobile Components"
  | "Automobiles"
  | "Banks"
  | "Beverages"
  | "Biotechnology"
  | "Broadline Retail"
  | "Building Products"
  | "Capital Markets"
  | "Chemicals"
  | "Commercial Services & Supplies"
  | "Communications Equipment"
  | "Construction & Engineering"
  | "Construction Materials"
  | "Consumer Finance"
  | "Consumer Staples Distribution & Retail"
  | "Containers & Packaging"
  | "Distributors"
  | "Diversified Consumer Services"
  | "Diversified REITs"
  | "Diversified Telecommunication Services"
  | "Electric Utilities"
  | "Electrical Equipment"
  | "Electronic Equipment, Instruments & Components"
  | "Energy Equipment & Services"
  | "Entertainment"
  | "Financial Services"
  | "Food Products"
  | "Gas Utilities"
  | "Ground Transportation"
  | "Health Care Equipment & Supplies"
  | "Health Care Providers & Services"
  | "Health Care REITs"
  | "Health Care Technology"
  | "Hotel & Resort REITs"
  | "Hotels, Restaurants & Leisure"
  | "Household Durables"
  | "Household Products"
  | "IT Services"
  | "Independent Power and Renewable Electricity Producers"
  | "Industrial Conglomerates"
  | "Industrial REITs"
  | "Insurance"
  | "Interactive Media & Services"
  | "Leisure Products"
  | "Life Sciences Tools & Services"
  | "Machinery"
  | "Marine Transportation"
  | "Media"
  | "Metals & Mining"
  | "Mortgage Real Estate Investment Trusts (REITs)"
  | "Multi-Utilities"
  | "Office REITs"
  | "Oil, Gas & Consumable Fuels"
  | "Paper & Forest Products"
  | "Passenger Airlines"
  | "Personal Care Products"
  | "Pharmaceuticals"
  | "Professional Services"
  | "Real Estate Management & Development"
  | "Residential REITs"
  | "Retail REITs"
  | "Semiconductors & Semiconductor Equipment"
  | "Software"
  | "Specialized REITs"
  | "Specialty Retail"
  | "Technology Hardware, Storage & Peripherals"
  | "Textiles, Apparel & Luxury Goods"
  | "Tobacco"
  | "Trading Companies & Distributors"
  | "Transportation Infrastructure"
  | "Water Utilities"
  | "Wireless Telecommunication Services";

export type GicsSubIndustry =
  | "Advertising"
  | "Aerospace & Defense"
  | "Agricultural & Farm Machinery"
  | "Agricultural Products & Services"
  | "Air Freight & Logistics"
  | "Airport Services"
  | "Alternative Carriers"
  | "Aluminum"
  | "Apparel Retail"
  | "Apparel, Accessories & Luxury Goods"
  | "Application Software"
  | "Asset Management & Custody Banks"
  | "Automobile Manufacturers"
  | "Automotive Parts & Equipment"
  | "Automotive Retail"
  | "Biotechnology"
  | "Brewers"
  | "Broadcasting"
  | "Broadline Retail"
  | "Building Products"
  | "Cable & Satellite"
  | "Cargo Ground Transportation"
  | "Casinos & Gaming"
  | "Coal & Consumable Fuels"
  | "Commercial & Residential Mortgage Finance"
  | "Commercial Printing"
  | "Commodity Chemicals"
  | "Communications Equipment"
  | "Computer & Electronics Retail"
  | "Construction & Engineering"
  | "Construction Machinery & Heavy Transportation Equipment"
  | "Construction Materials"
  | "Consumer Electronics"
  | "Consumer Finance"
  | "Consumer Staples Merchandise Retail"
  | "Copper"
  | "Data Center REITs"
  | "Data Processing & Outsourced Services"
  | "Distillers & Vintners"
  | "Distributors"
  | "Diversified Banks"
  | "Diversified Capital Markets"
  | "Diversified Chemicals"
  | "Diversified Financial Services"
  | "Diversified Metals & Mining"
  | "Diversified REITs"
  | "Diversified Real Estate Activities"
  | "Diversified Support Services"
  | "Drug Retail"
  | "Education Services"
  | "Electric Utilities"
  | "Electrical Components & Equipment"
  | "Electronic Components"
  | "Electronic Equipment & Instruments"
  | "Electronic Manufacturing Services"
  | "Environmental & Facilities Services"
  | "Fertilizers & Agricultural Chemicals"
  | "Financial Exchanges & Data"
  | "Food Distributors"
  | "Food Retail"
  | "Footwear"
  | "Forest Products"
  | "Gas Utilities"
  | "Gold"
  | "Health Care Distributors"
  | "Health Care Equipment"
  | "Health Care Facilities"
  | "Health Care REITs"
  | "Health Care Services"
  | "Health Care Supplies"
  | "Health Care Technology"
  | "Heavy Electrical Equipment"
  | "Highways & Railtracks"
  | "Home Furnishings"
  | "Home Improvement Retail"
  | "Homebuilding"
  | "Homefurnishing Retail"
  | "Hotel & Resort REITs"
  | "Hotels, Resorts & Cruise Lines"
  | "Household Appliances"
  | "Household Products"
  | "Housewares & Specialties"
  | "Human Resource & Employment Services"
  | "IT Consulting & Other Services"
  | "Independent Power Producers & Energy Traders"
  | "Industrial Conglomerates"
  | "Industrial Gases"
  | "Industrial Machinery & Supplies & Components"
  | "Industrial REITs"
  | "Insurance Brokers"
  | "Integrated Oil & Gas"
  | "Integrated Telecommunication Services"
  | "Interactive Home Entertainment"
  | "Interactive Media & Services"
  | "Internet Services & Infrastructure"
  | "Investment Banking & Brokerage"
  | "Leisure Facilities"
  | "Leisure Products"
  | "Life & Health Insurance"
  | "Life Sciences Tools & Services"
  | "Managed Health Care"
  | "Marine Ports & Services"
  | "Marine Transportation"
  | "Metal, Glass & Plastic Containers"
  | "Mortgage REITs"
  | "Motorcycle Manufacturers"
  | "Movies & Entertainment"
  | "Multi-Family Residential REITs"
  | "Multi-Sector Holdings"
  | "Multi-Utilities"
  | "Multi-line Insurance"
  | "Office REITs"
  | "Office Services & Supplies"
  | "Oil & Gas Drilling"
  | "Oil & Gas Equipment & Services"
  | "Oil & Gas Exploration & Production"
  | "Oil & Gas Refining & Marketing"
  | "Oil & Gas Storage & Transportation"
  | "Other Specialized REITs"
  | "Other Specialty Retail"
  | "Packaged Foods & Meats"
  | "Paper & Plastic Packaging Products & Materials"
  | "Paper Products"
  | "Passenger Airlines"
  | "Passenger Ground Transportation"
  | "Personal Care Products"
  | "Pharmaceuticals"
  | "Precious Metals & Minerals"
  | "Property & Casualty Insurance"
  | "Publishing"
  | "Rail Transportation"
  | "Real Estate Development"
  | "Real Estate Operating Companies"
  | "Real Estate Services"
  | "Regional Banks"
  | "Reinsurance"
  | "Renewable Electricity"
  | "Research & Consulting Services"
  | "Restaurants"
  | "Retail REITs"
  | "Security & Alarm Services"
  | "Self-Storage REITs"
  | "Semiconductor Materials & Equipment"
  | "Semiconductors"
  | "Silver"
  | "Single-Family Residential REITs"
  | "Soft Drinks & Non-alcoholic Beverages"
  | "Specialized Consumer Services"
  | "Specialized Finance"
  | "Specialty Chemicals"
  | "Steel"
  | "Systems Software"
  | "Technology Distributors"
  | "Technology Hardware, Storage & Peripherals"
  | "Telecom Tower REITs"
  | "Textiles"
  | "Timber REITs"
  | "Tires & Rubber"
  | "Tobacco"
  | "Trading Companies & Distributors"
  | "Transaction & Payment Processing Services"
  | "Water Utilities"
  | "Wireless Telecommunication Services";

export type GicsSubIndustryData = {
  subIndustry: GicsSubIndustry;
};

export type GicsIndustryData = {
  industry: GicsIndustry;
  subIndustries: GicsSubIndustryData[];
};

export type GicsIndustryGroupData = {
  industryGroup: GicsIndustryGroup;
  industries: GicsIndustryData[];
};

export type GicsSectorData = {
  sector: GicsSector;
  industryGroups: GicsIndustryGroupData[];
};
