import type { MetricApplicability } from "./types";

export const metricApplicability: MetricApplicability[] = [
  {
    industry: "Energy Equipment & Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Oil, Gas & Consumable Fuels",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Chemicals",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Construction Materials",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Containers & Packaging",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Metals & Mining",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Paper & Forest Products",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Aerospace & Defense",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Building Products",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Construction & Engineering",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Electrical Equipment",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Industrial Conglomerates",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Machinery",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Trading Companies & Distributors",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Commercial Services & Supplies",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Professional Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Air Freight & Logistics",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Passenger Airlines",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Marine Transportation",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Ground Transportation",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Transportation Infrastructure",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Automobile Components",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Automobiles",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Household Durables",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Leisure Products",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Textiles, Apparel & Luxury Goods",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Hotels, Restaurants & Leisure",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Diversified Consumer Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Distributors",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Broadline Retail",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Specialty Retail",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Consumer Staples Distribution & Retail",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Beverages",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Food Products",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Tobacco",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Household Products",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Personal Care Products",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Health Care Equipment & Supplies",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Health Care Providers & Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Health Care Technology",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Biotechnology",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Pharmaceuticals",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Life Sciences Tools & Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Banks",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: false,
    debtToEquityRatioMrq: false,
    interestCoverageRatioTtm: false,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: false,
  },
  {
    industry: "Financial Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: false,
    debtToEquityRatioMrq: false,
    interestCoverageRatioTtm: false,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: false,
  },
  {
    industry: "Consumer Finance",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: false,
    debtToEquityRatioMrq: false,
    interestCoverageRatioTtm: false,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Capital Markets",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: false,
    debtToEquityRatioMrq: false,
    interestCoverageRatioTtm: false,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Mortgage Real Estate Investment Trusts (REITs)",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: false,
    debtToEquityRatioMrq: false,
    interestCoverageRatioTtm: false,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Insurance",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: false,
    currentRatioMrq: false,
    debtToEquityRatioMrq: false,
    interestCoverageRatioTtm: false,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "IT Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Software",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Communications Equipment",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Technology Hardware, Storage & Peripherals",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Electronic Equipment, Instruments & Components",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Semiconductors & Semiconductor Equipment",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Diversified Telecommunication Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Wireless Telecommunication Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Media",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Entertainment",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Interactive Media & Services",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Electric Utilities",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Gas Utilities",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Multi-Utilities",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Water Utilities",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Independent Power and Renewable Electricity Producers",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Diversified REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Industrial REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Hotel & Resort REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Office REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Health Care REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Residential REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Retail REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Specialized REITs",
    returnOnEquityTtm: true,
    netProfitMarginTtm: false,
    operatingProfitMarginTtm: false,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: false,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
  {
    industry: "Real Estate Management & Development",
    returnOnEquityTtm: true,
    netProfitMarginTtm: true,
    operatingProfitMarginTtm: true,
    currentRatioMrq: true,
    debtToEquityRatioMrq: true,
    interestCoverageRatioTtm: true,
    dividendYieldTtm: true,
    dividendPayoutRatioTtm: true,
    priceToEarningsRatioTtm: true,
    priceToBookRatioMrq: true,
    priceToSalesRatioTtm: true,
  },
];
